From beec026014e3e61cf8b686654006c11dbba1b43e Mon Sep 17 00:00:00 2001
From: "cheng.tang" <tangch318@gmail.com>
Date: Tue, 1 Nov 2016 15:44:36 +0800
Subject: [PATCH 70/73] Fix error when invoke firewall_deleted rpc function

Fixes: redmine #8884

Signed-off-by: cheng.tang <tangch318@gmail.com>
Signed-off-by: Hunt Xu <mhuntxu@gmail.com>
---
 neutron/services/firewall/fwaas_plugin.py | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/neutron/services/firewall/fwaas_plugin.py b/neutron/services/firewall/fwaas_plugin.py
index e79fd81..4d7aaf8 100644
--- a/neutron/services/firewall/fwaas_plugin.py
+++ b/neutron/services/firewall/fwaas_plugin.py
@@ -63,7 +63,12 @@ class FirewallCallbacks(n_rpc.RpcCallback):
         """Agent uses this to indicate firewall is deleted."""
         LOG.debug(_("firewall_deleted() called"))
         with context.session.begin(subtransactions=True):
-            fw_db = self.plugin._get_firewall(context, firewall_id)
+            try:
+                fw_db = self.plugin._get_firewall(context, firewall_id)
+            except fw_ext.FirewallNotFound:
+                # in this case, firewall has been deleted by other agent
+                return
+
             # allow to delete firewalls in ERROR state
             if fw_db.status in (const.PENDING_DELETE, const.ERROR):
                 self.plugin.delete_db_firewall_object(context, firewall_id)
-- 
2.10.2

